version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      # MYSQL_USER: wordpress
      # MYSQL_PASSWORD: wordpress
    ports:
      - 33061:3306
    networks:
      - wp-network
    
  wordpress:
    depends_on:
      - db
    build:
      dockerfile: ./docker-files/wordpress.dockerfile
      context: .
    volumes:
      - wordpress_data:/var/www/html
      - ./docker-files/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./wp-content:/var/www/html/wp-content
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wp-network
networks:
  wp-network:
volumes:
  db_data: {}
  wordpress_data: {}
